title: Daphne Ticola
description: >
  Instructional Systems Designer specializing in learner-centered,
  performance-focused instructional solutions.
 
  url: "https://daphneticola.github.io"
baseurl: "/daphne-ticola.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: Daphne Ticola
  avatar: /assets/images/avatar.jpg
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/daphne-ticola3"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      header:
        nav: "main"

