title: Daphne Ticola Designs
description: "Instructional Systems Designer specializing in learner-centered, performance-focused instructional solutions."

url: "https://daphneticola.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: Daphne Ticola, M.Ed.
  avatar: "/assets/images/daphnejpg.jpg"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/daphneticola"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      header:
        nav: "main"
